### ISSUE TITLE
Unable to crawl with Videos

### ISSUE THREAD

**Issue by laurent-d** [nacimgoura/instagram-profilecrawl#1]
Hi @nacimgoura ,

Thanks for you script, it work great except when there is video in the feed.

Cheers

Laurent

**Comment by nacimgoura** [comment]
Hello, 
I have not tested with the videos :pensive: 
I fix it quickly.

Thanks you for your feedback!

**Comment by nacimgoura** [comment]
Good news @laurent-d ,
The script now correctly retrieves the videos.

Thanks!

**Comment by laurent-d** [comment]
Woww great, Thanks a lot, it's a big improvement @nacimgoura !!
