### ISSUE TITLE
support phantomjs

### ISSUE THREAD

**Issue by coutliuxing** [nacimgoura/instagram-profilecrawl#11]
hi~i am using you project , but i am in china,so can't  install chromedriver. could you tall me how to let it support phantomjs?

**Comment by nacimgoura** [comment]
Good morning. Hello,
Sorry for the late reply.
My script uses the element overview of dom but this feature is not supported by phantomjs (The last time I tested with phantomjs).
Why can't you install chromedriver?

**Comment by coutliuxing** [comment]
Because in China, all access to Google is not allowed. There are sometimes problems with the use of VPN.
