### ISSUE TITLE
Tests and Issues

### ISSUE THREAD

**Issue by eek** [nacimgoura/instagram-profilecrawl#12]
Gave it a try today, the Selenium method dies with an error, every time.
The API Method works, but all posts are marked with the `1970-01-17` date.

**Comment by eek** [comment]
I have seen the date was already fixed, but a new version wasn't updated on npm

**Comment by nacimgoura** [comment]
Hello, I completely forgot to update to npm. I'll do it tomorrow asap :smiley:

**Comment by eek** [comment]
Awesome @nacimgoura!

Please also include #13 in that release 😁 

And there's also an issue when running stats for multiple profiles, and outputs just a file, with the post from all the profiles but only the main profile in the file.

**Comment by nacimgoura** [comment]
I updated npm.
