### ISSUE TITLE
Make it easier to call programatically

### ISSUE THREAD

**Issue by marcospgp** [nacimgoura/instagram-profilecrawl#16]
It would be great if we could call the script using an attribute with the method choice (api or selenium) instead of selecting with arrows and pressing enter. Something like:

`instagram-profilecrawl --method="api"` or `instagram-profilecrawl --method="selenium"`

Another good thing to have would be a way to choose the filename for the result, perhaps with another parameter. It would also be nice to have the default name be "profile-\<name\>" instead of "profile \
\<name\>", because spaces in filenames can be problematic.

These changes would make it easier to use this inside scripts instead of just manually through the console!

Cheers 😄

**Comment by nacimgoura** [comment]
yes it's a good idea, I try to do it asap.

**Comment by marcospgp** [comment]
Small note, the parameters don't need quotes, so it would be `instagram-profilecrawl --method=api` or `instagram-profilecrawl --method=selenium` instead, or whatever else you prefer!

**Comment by nacimgoura** [comment]
It's done!

**Comment by marcospgp** [comment]
Awesome! Nice work 👍
