### ISSUE TITLE
Add ability to set a "since" parameter

### ISSUE THREAD

**Issue by marcospgp** [nacimgoura/instagram-profilecrawl#17]
For people who want to use this utility more than once on the same instagram account, it would be awesome to be able to set a parameter that would tell the script to only crawl posts that are newer than a given date or post (basically using the date that a particular post was uploaded).

**Comment by nacimgoura** [comment]
You can create a pull request if you want 😃

**Comment by marcospgp** [comment]
I will as soon as I have the time! Just leaving this here until then in case anyone would like to go ahead 😄
