### ISSUE TITLE
Include comments in output

### ISSUE THREAD

**Issue by marcospgp** [nacimgoura/instagram-profilecrawl#18]
Something that would be nice to have. I'll do this myself when I get the chance, in case no one wants to go ahead until then 😄

**Comment by nacimgoura** [comment]
Hello,
I tried to do it at first but Instagram has a limit on the number of visible comments and the crawl time is considerably increased :sad:

**Comment by marcospgp** [comment]
I see, let's keep this in the backlog then?

**Comment by nacimgoura** [comment]
Yeah, I'll think about it later. There is also the api that does not return any comments.
