### ISSUE TITLE
stays in Init API

### ISSUE THREAD

**Issue by R0cKET** [nacimgoura/instagram-profilecrawl#22]

**Comment by nacimgoura** [comment]
thank you for the information. I'm watching this tomorrow.

**Comment by R0cKET** [comment]
instagram change the response of the api 🤨

**Comment by santwijaya** [comment]
I found same issue.

**Comment by nacimgoura** [comment]
the API response has changed. I corrected that soon.

**Comment by nacimgoura** [comment]
It's fixed!
