### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by alejandronanez** [nacimgoura/instagram-profilecrawl#23]
Hello @nacimgoura, thanks for creating this tool!

How do you feel about adding prettier + editor config to the project? If that sounds good to you, I can create a PR.

Thanks!

**Comment by nacimgoura** [comment]
editorconfig comes into conflict with eslint it seems to me. I've never used loaner but if you want you can create a pr :smile:

**Comment by alejandronanez** [comment]
Sounds good! I’ll create a pr then :)
