### ISSUE TITLE
Is it possible to crawl from private account?

### ISSUE THREAD

**Issue by santwijaya** [nacimgoura/instagram-profilecrawl#25]
I just curious for this context. Is it possible to crawl from private account? I've try for some private account and this program just return basic information and not for posts. Is it possible to do this case, even though I have instagram account that follow the account.

**Comment by nacimgoura** [comment]
Hello,
Currently I do not allow connection so it is impossible to recover private account data.
But if you want, you can create a pr and allow the connection before the crawl.

**Comment by santwijaya** [comment]
I have do this task for my research in undergraduate program to make a behavioral analytic from social media. I've done to get the data from twitter but not for instagram.
