### ISSUE TITLE
small thing

### ISSUE THREAD

**Issue by shad0xfox** [nacimgoura/instagram-profilecrawl#26]
in file <api.js>
line 95~97

post.edge_media_to_caption.edges[0].node.text  <-- this

because <post.edge_media_to_caption.edges > may be empty
need some check , or it would stop here,
I add something like 
mentions:  (post.edge_media_to_caption.edges.length)?utils.getMentions(post.edge_media_to_caption.edges[0].node.text) : "",

Then it work

thank you

**Comment by nacimgoura** [comment]
Fixed by https://github.com/nacimgoura/instagram-profilecrawl/commit/c5c3c7f640648d9a8fa712152eba944bc7356fda
