### ISSUE TITLE
Tool is broken

### ISSUE THREAD

**Issue by marcospgp** [nacimgoura/instagram-profilecrawl#28]
I updated to the latest version and cannot successfully crawl a profile anymore.

Can anyone try running the crawler with `--method=api` on profile `marsquest` and see if it works?

**Comment by marcospgp** [comment]
This happens as many times as I try running the crawler, so it seems like it could really be a bug in the code 😄

**Comment by nacimgoura** [comment]
I was just correcting him. You can edit the comment instead of creating new ones please 🙇

**Comment by marcospgp** [comment]
Sorry! Thank you for the fast reply 😄
