### ISSUE TITLE
Unable to start selenium server!

### ISSUE THREAD

**Issue by trzytematyczna** [nacimgoura/instagram-profilecrawl#29]
Hi, I am trying to run the selenium method (API method runs without problems), I installed it beforehand, but while executing the example `instagram-profilecrawl nacimgoura --thod=selenium`, I get an error `✖ Unable to start selenium server!`. Any clues what can be wrong?

**Comment by nacimgoura** [comment]
hello, did you do this ? :
‘‘‘
npm install selenium-standalone@latest -g selenium-standalone install
‘‘‘

**Comment by trzytematyczna** [comment]
yep!

**Comment by nacimgoura** [comment]
Okay, thanks for the information. I'm watching this soon :wink:

**Comment by nacimgoura** [comment]
Currently, crawl doesn't work for public profiles. I'll correct that when I have time. It work properly with privates profiles.
