### ISSUE TITLE
✖ Cannot read property 'length' of null when no description

### ISSUE THREAD

**Issue by laurent-d** [nacimgoura/instagram-profilecrawl#3]
Hi @nacimgoura !
Your new commits seems to make a side effect when i try your app on my own account with no post description: 
$ instagram-profilecrawl _laurent_la
✔ Profile successfully loaded for _laurent_la!
✖ Cannot read property 'length' of null
Have a good day !

**Comment by nacimgoura** [comment]
Hi @laurent-d !
Yes I encountered the same problem with your account.
I made a change, tell me if it's resolved for you.
Have a good day !

**Comment by laurent-d** [comment]
So good thanks a lot 💯
