### ISSUE TITLE
Tool is broken

### ISSUE THREAD

**Issue by R0cKET** [nacimgoura/instagram-profilecrawl#30]

**Comment by nacimgoura** [comment]
@R0cKET why do you say that ?

**Comment by R0cKET** [comment]
$ instagram-profilecrawl instagram
HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/usr/lib/node_modules/instagram-profilecrawl/node_modules/got/index.js:372:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by hanjukim** [comment]
@nacimgoura interesting.. that it seems they stopped to serve https://www.instagram.com/{username}?__a=1 from my side. Is this method still working on your environment?

**Comment by nacimgoura** [comment]
I have a 403 error now too.

**Comment by hanjukim** [comment]
padding ?__a=1 method is still working only for post link, https://www.instagram.com/p/{shortcode}/?__a=1
As far as I know there are two ways to pass this.

1. sessionid cookie which is that we have to login.
2. x-instagram-gis http header without login. This is a string made by hash function with XHR Signature:CSRF token:Stringified variables(for graphql query)

**Comment by nacimgoura** [comment]
Thanks @hanjukim ! Currently I work to make a new version which use puppeteer instead of selenium. After this I would look at the instagram api.

**Comment by hanjukim** [comment]
What I mean to pass is to avoid 403 Forbbiden
