### ISSUE TITLE
No treatment when posts > 1000

### ISSUE THREAD

**Issue by laurent-d** [nacimgoura/instagram-profilecrawl#4]
Hi @nacimgoura !
When the number of posts is bigger than 1000, your script stop without treatment.
instagram-profilecrawl jamieoliver
✔ Profile successfully loaded for jamieoliver!
✔ File created with success!

**Comment by laurent-d** [comment]
I think it the same for the likes, if the likes is bigger than 999, the json display null.

**Comment by nacimgoura** [comment]
Hi again @laurent-d .
When the number is too high it is replaced by a letter, which I did not know. I have modified and it will have to be good.

**Comment by laurent-d** [comment]
@nacimgoura Thanks for support.
It seems does not make effect but it make an error about the replace fonction  : 
 instagram-profilecrawl bigmammagroup
✔ Profile successfully loaded for bigmammagroup!
✖ number.replace is not a function

**Comment by nacimgoura** [comment]
I work on a solution, I will notify you when it will be good.

**Comment by nacimgoura** [comment]
It seems that it works now. I'm waiting for your feedback!

**Comment by laurent-d** [comment]
Hi @nacimgoura that's work 👍  but all like field are at 0 👎 
Thanks a lot for the amazing support.
Have a good day

**Comment by nacimgoura** [comment]
I can't reproduce the bug.
What account do you use?

**Comment by laurent-d** [comment]
It seems it's the same issue of thousand post, when the number of like > 999, it write 0
I test on these accounts : alainducasse, bigmammagroup
For normal account with less like it works.

**Comment by nacimgoura** [comment]
I tested with bigmammagroup, alainducasse and emmawatson, too.
I didn't encounter any worries.
I just made a new commit with examples : https://github.com/nacimgoura/instagram-profilecrawl/tree/master/examples
I tested several times, I have 0 likes only for the videos, which is normal.

**Comment by laurent-d** [comment]
Incomprehensible !!! : http://laurent.la/profile-emmawatson.json
I made a fresh update of nodejs (v6.10.2) and of your app (1.3.1).
My OS is Sierra, Chrome is updated (58.)
Sorry about all these issues.
Hope that it works for others.

**Comment by nacimgoura** [comment]
I finish adding a new feature and test with the same version of nodeJS as you. I was testing with nodeJS 4.8 to test compatibility. 
I'll keep you informed.

**Comment by nacimgoura** [comment]
@laurent-d , I have updated the program, maybe it will work for you now.

**Comment by laurent-d** [comment]
Nop :(, it's a mac issue perhaps

**Comment by nacimgoura** [comment]
Completely remove the program and download it again. Behavior should be the same depending on the os. But I'll try something and tell you when it's good.

**Comment by nacimgoura** [comment]
@laurent-d Can you clone this project and replace index.js with https://gist.github.com/nacimgoura/e9a743e02f15f5a33f637631424f0830 and test with : ./index.js emmawatson

Tell me if you still have the number of likes equal to 0.

**Comment by laurent-d** [comment]
@nacimgoura , It seems work great !!! Thanks a lot.
See : http://laurent.la/profile-emmawatson.json
It miss a 0 for thousand of likes , 799K write 79900 but it works.
Some of comments are null but its a great improvement 🥇 
Thanks again

**Comment by nacimgoura** [comment]
The null comments have gone randomly, which is really strange. I don't have this problem but I will think about a fix.

**Comment by laurent-d** [comment]
I made a second test with alainducasse : http://laurent.la/profile-alainducasse.json
Only likes < 999 works Very strange.
Take your time for the issue !

**Comment by nacimgoura** [comment]
Hi @laurent-d ,
Can you test with the new version? I can not really test on my computer because I do not encounter the bug but I tried to understand its origin.
I await your feedback.

**Comment by laurent-d** [comment]
Hi @nacimgoura !
Yes sure, for emma, likes works like a charm, comments bug at the third post (i tried twice) any memory issue ?) : http://laurent.la/profile-emmawatson.json
for alain : likes don't work but comments are goods very strange : http://laurent.la/profile-alainducasse.json
For smaller accounts its good
Do not hesitate if you want more test!!

**Comment by nacimgoura** [comment]
I finally understand where it comes from, I'll try to correct it if that's what I think.

**Comment by laurent-d** [comment]
Good news 👍 👍 👍 👍 👍 👍

**Comment by nacimgoura** [comment]
@laurent-d ,
I released the new version. If it works now it means that the error came from the fact that your chrome browser is in French and the numbers were displayed differently than in English.
And that's also why I couldn't have the error. I'm French too but my browser is in English.

**Comment by laurent-d** [comment]
@nacimgoura.
It works 💯  
Fabulous thanks for you awesome work and support !!!
The error on the python script is surely due to this.
I will make make i tiny script to use the data and order it.
Thanks again

**Comment by nacimgoura** [comment]
No worries, it allowed me to correct the bugs.
If you are thinking of improvements, you can make a pull request.
