### ISSUE TITLE
Reference missing ?

### ISSUE THREAD

**Issue by khanof89** [nacimgoura/instagram-profilecrawl#41]
Dear Author, I appreciate that you took time to write this script in javascript, I also believe that this is your original work but I think it is inspired by https://github.com/timgrossmann/instagram-profilecrawl if this is the case it is always a good practice to refer to the repository which inspired you to do so.

**Comment by nacimgoura** [comment]
Yes, thank you for your feedback. Indeed in V1 my work was inspired by his work and I used selenium as well. But in the V2 I now use puppeteer and its operation is very different from the V1. That's why I had to build everything from scratch.
