### ISSUE TITLE
Problem paging (or so it seems)

### ISSUE THREAD

**Issue by vernak2539** [nacimgoura/instagram-profilecrawl#5]
I'm getting an issue and it looks like this

```
[vernacchia:~/Coding/testing]$ node node_modules/instagram-profilecrawl/index.js
✔ Profile successfully loaded for vernak2539!
✖ An element could not be located on the page using the given search parameters.
```

It get's to around the 20th step `⠇ Advancement of the first step : 20/203`

any help would be great. 

I have a little trouble installing it globally (problem starting selenium), so i had to install it and modify the index file, hence the reason for my command line approach

**Comment by nacimgoura** [comment]
Hello @vernak2539 ,
I didn't encounter any problems with your account but I increased the pause time. I have updated the program, I hope it will work at home. I am waiting for your feedback.

**Comment by vernak2539** [comment]
It still did not work unfortunately. was running on node 7.1 if that makes a difference

**Comment by nacimgoura** [comment]
I tried with nodejs 7.1 and I don't have this bug. The program always stops at the 20th ? What happens on the browser just before the bug?

**Comment by nacimgoura** [comment]
Hi @vernak2539 , can you try again ?

**Comment by vernak2539** [comment]
It seems to get stuck at 24 still, but doesn't quit as fast

```
✔ Profile successfully loaded for vernak2539!
⠸ Advancement of the first step : 24/205
```

It's not loading the next page, so I think it's having trouble scrolling or something

**Comment by nacimgoura** [comment]
Have you tested with the API ?
Test with the API and said me your feedback.
