### ISSUE TITLE
Is is possible to use from React Native?

### ISSUE THREAD

**Issue by hiteshi-pawan** [nacimgoura/instagram-profilecrawl#6]
Hello,

Is it possible to use this module from React Native? I want to crawl a user's profile without having him/her to login.

It would be great if you can provide any document for this.

**Comment by nacimgoura** [comment]
Hello, I have never used native react but I do not think this is possible. I created this module thinking that it would be used only on command line. Want to do what exactly? With my program I retrieve the data of this url: https://www.instagram.com/beyonce/?__a=1
